services:
  go2rtc:
    container_name: ${name_container}
    image: alexxit/go2rtc
    network_mode: host       # important for WebRTC, HomeKit, UDP cameras
    privileged: true         # only for FFmpeg hardware transcoding
    restart: unless-stopped  # autorestart on fail or config change from WebUI
    environment:
      - TZ=${TZ}  # timezone in logs
    volumes:
      - "${folder}:/config"   
