version: "3.8"
services:
  dashy:
    image: lissy93/dashy
    container_name: ${name_container}
    volumes:
      - ${folder}/conf.yml:/app/user-data/conf.yml
      - /home/docker/dashy/icons:/app/public/item-icons/
    ports:
      - ${port}:8080
    environment:
      - NODE_ENV=production
      - UID=1000
      - GID=1000
    restart: unless-stopped
    labels:
      - "diun.enable=true"
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

