version: '3.8'
services:
  zigbee:
    container_name: zigbee

    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    volumes:
      - /home/docker/zigbee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8888:8080
    environment:
      - TZ=Europe/Paris
    devices:
      - /dev/serial/by-id/usb-Silicon_Labs_Sonoff_Zigbee_3.0_USB_Dongle_Plus_0001-if00-port0:/dev/ttyACM0
